blank_issues_enabled: false
contact_links:
  - name: Silocleaner project information
    url: https://github.com/lindemannm/Silocleaner/blob/main/.github/ISSUE_TEMPLATE/project.md
    about: Read the project's current scope and contribution guidance.
  - name: ❓ Ask a Question
    url: https://github.com/lindemannm/Silocleaner/discussions/new?category=general
    about: Ask the community for help
  
